apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-app-v2-deployment
  labels:
    app: web-app-v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app-v2
  template:
    metadata:
      labels:
        app: web-app-v2
    spec:
      containers:
        - name: web-app-v2
          image: maulick/argocd:2.0
          ports:
            - containerPort: 82
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}         # pause indefinitely
      - setWeight: 20
      - pause: {duration: 20s}
      - setWeight: 30
      - pause: {duration: 20s}
      - setWeight: 40
      - pause: {duration: 20s}
      - setWeight: 50
      - pause: {duration: 20s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 70
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
      - setWeight: 90
      - pause: {duration: 20s}
