apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-app-V2-deployment
  labels:
    app: web-app-V2
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web-app-V2
  template:
    metadata:
      labels:
        app: web-app-V2
    spec:
      containers:
        - name: web-app-V2
          image: maulick/argocd:2.0
          ports:
            - containerPort: 82
